paths:
  /api/products/:
    get:
      summary: "Get a list of products"
      tags:
        - Products
      responses:
        "200":
          description: "Products successfully obtained from the database."
          content:
           application/json:
            schema:
             type: array
             items:
              $ref: "#components/schemas/Products"
        "500":
          description: "Internal server error, usually database connection failure or faulty query."
    post:
      summary: "Create products"
      tags:
        - Products
      responses:
        "200":
          description: "Products successfully created in the database."
        "400":
          description: "Fields incompleted or not valid"
        "500":
          description: "Internal server error, usually database connection failure or faulty query."
  /api/products/{pid}:
    get:
      summary: "Get product by id"
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product id to search
          schema:
            $type: string
      responses:
        "200":
          description: "Product successfully obtained from the database."
        "404":
          description: "Product don't found."
        "500":
          description: "Internal server error, usually database connection failure or faulty query."
    put:
      summary: "Update product by id"
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product id to update
          schema:
            $type: string
      responses:
        "200":
          description: "Product updated successfully."
        "400":
          description: "Fields incompleted or not valid"
        "404":
          description: "Product don't found."
        "500":
          description: "Internal server error, usually database connection failure or faulty query."
    delete:
      summary: "Delete product by id"
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product id to delete
          schema:
            $type: string
      responses:
        "200":
          description: "Product deleted successfully."
        "404":
          description: "Product don't found."
        "500":
          description: "Internal server error, usually database connection failure or faulty query."

components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: string
          description: Id generated by MongoDB
        title:
          type: string
          description: The title of the product
        description:
          type: string
          description: A description of the product
        price:
          type: number
          description: The price of the product
        thumbnail:
          type: string
          description: URL or path to the product's thumbnail image
        code:
          type: string
          description: A unique code associated with the product
        stock:
          type: integer
          description: The available stock quantity of the product
        category:
          type: string
          description: The category to which the product belongs
        status:
          type: boolean
          default: true
          description: The status of the product (default is true for active)
      required:
        - title
        - description
        - price
        - thumbnail
        - code
        - stock
        - category
      example:
        _id: ObjectId(123456ABC)
        title: "product"
        description: "product description"
        price: 100
        thumbnail: "image url"
        code: "00001"
        stock: 20
        category: "box"
